"""Generate the deterministic, license-safe Phase 1 prototype data pack."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = ROOT / "data"
TEAM_FILE = DEFAULT_OUTPUT_DIR / "teams.json"

POSITION_ORDER = [
    "GK",
    "GK",
    "DF",
    "DF",
    "DF",
    "DF",
    "DF",
    "DF",
    "MF",
    "MF",
    "MF",
    "MF",
    "MF",
    "MF",
    "FW",
    "FW",
    "FW",
    "FW",
]

POSITION_ATTRIBUTES = {
    "GK": [
        "reflexes",
        "handling",
        "aerial_control",
        "one_on_one",
        "positioning",
        "distribution",
        "decisions",
    ],
    "DF": [
        "positioning",
        "marking",
        "tackling",
        "interceptions",
        "aerial",
        "pace",
        "strength",
        "passing",
    ],
    "MF": [
        "passing",
        "vision",
        "decisions",
        "ball_control",
        "press_resistance",
        "stamina",
        "work_rate",
        "tackling",
        "long_shots",
    ],
    "FW": [
        "finishing",
        "composure",
        "off_ball_movement",
        "dribbling",
        "acceleration",
        "strength",
        "aerial",
        "decisions",
    ],
}

POSITION_ROLES = {
    "GK": "Goalkeeper",
    "DF": "Defender",
    "MF": "Midfielder",
    "FW": "Forward",
}

POSITION_BIAS = {"GK": -2, "DF": 0, "MF": 1, "FW": 2}


def _write_json(path: Path, payload: dict) -> None:
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def _attribute_value(team_strength: int, team_index: int, player_index: int, position: str, attribute_index: int) -> int:
    base = team_strength + POSITION_BIAS[position]
    stable_variation = ((team_index * 17 + player_index * 7 + attribute_index * 3) % 13) - 6
    return max(1, min(99, base + stable_variation))


def _build_players(team_payload: dict) -> list[dict]:
    players: list[dict] = []
    for team_index, team in enumerate(team_payload["teams"]):
        for player_index, position in enumerate(POSITION_ORDER):
            attributes = {
                attribute: _attribute_value(
                    int(team["strength"]),
                    team_index,
                    player_index,
                    position,
                    attribute_index,
                )
                for attribute_index, attribute in enumerate(POSITION_ATTRIBUTES[position])
            }
            players.append(
                {
                    "id": f"{team['id']}_prototype_{player_index + 1:02d}",
                    "team_id": team["id"],
                    "display_name": f"{team['name']} Prototip {player_index + 1:02d}",
                    "position": position,
                    "role": POSITION_ROLES[position],
                    "age": 18 + ((team_index * 5 + player_index * 3) % 17),
                    "preferred_foot": "left" if (team_index + player_index) % 4 == 0 else "right",
                    "nationality_group": "domestic" if (team_index + player_index) % 5 else "foreign",
                    "national_team_eligible": (team_index + player_index) % 5 != 0,
                    "attributes": attributes,
                }
            )
    return players


def _build_rules(team_count: int) -> dict:
    return {
        "schema_version": "0.1.0",
        "season": "2026-2027",
        "source_type": "project_decision",
        "source_note": "Competition values reflect the repository's researched 2026-2027 prototype rules. They are kept as data so a future season can use another rule set.",
        "competition": {
            "team_count": team_count,
            "rounds": 2,
            "weeks": 34,
            "matchday_squad_size": 21,
            "max_substitutions": 5,
        },
        "squad": {
            "max_a_team_players": 28,
            "max_foreign_players": 14,
            "min_national_team_eligible_players": 14,
            "min_young_national_team_eligible_players": 4,
            "max_goalkeepers": 3,
            "min_eligible_goalkeepers": 2,
        },
    }


def generate(output_dir: Path) -> tuple[Path, Path]:
    team_payload = json.loads(TEAM_FILE.read_text(encoding="utf-8"))
    output_dir.mkdir(parents=True, exist_ok=True)

    players_payload = {
        "schema_version": "0.1.0",
        "season": team_payload["season"],
        "source_type": "synthetic",
        "source_note": "All player identities and attributes in this file are deterministic prototype data generated by tools/generate_synthetic_data.py. They are not official ratings or real player records.",
        "players": _build_players(team_payload),
    }
    rules_payload = _build_rules(len(team_payload["teams"]))

    players_path = output_dir / "players.json"
    rules_path = output_dir / "game_rules.json"
    _write_json(players_path, players_payload)
    _write_json(rules_path, rules_payload)
    return players_path, rules_path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for players.json and game_rules.json (default: data/)",
    )
    args = parser.parse_args()
    players_path, rules_path = generate(args.output_dir)
    print(f"Generated {players_path}")
    print(f"Generated {rules_path}")


if __name__ == "__main__":
    main()
